[package]
name = "chat_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
sqlx = { version = "0.8.2" , features = [
    "mysql",
    "runtime-tokio"
]}
dotenvy = "0.15.7"
env_logger = "0.11.5"
log = "0.4.22"