version: "3.8"

services:
  mysql:
    image: mysql:9.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_database
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: chat_password
    ports:
      - "3306:3306"  # Expose le port 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
